### ISSUE TITLE
Some hot keys don't work on Win7 or Win10 1803

### ISSUE THREAD

**Issue by WhiredPlanck** [Aegisub/Aegisub#111]
For example, when I press the Enter key, the software should has accepted the changes and moved to the next line.But actually it doesn't work. And many hot keys don't work just like the Enter key. I have tried to find an effective solution to this problem on the Internet but I failed.
This problem has made me disappointed for a long time. Sincerely hope someone can help me ~! : )

**Comment by ilko-k** [comment]
Does it occurs on a fresh system? You may have some conflicts

**Comment by antioncodec** [comment]
> 
> 
> Does it occurs on a fresh system? You may have some conflicts
It occurs not only on a fresh system but also on a old system. At first these keys can work,but after using the software 3~5 times, the issue occurs.

**Comment by ilko-k** [comment]
Your issue makes me think to a hardware problem. Try a different keyboard at first. It might be the motherboard as well, related to USB/PS2 juice or whatever it is. The chance that the problem comes from aegusub is very low IMO.

**Comment by FichteFoll** [comment]
I seem to remember that you can't bind anything to the enter key, but that doesn't explain other keys not workig.

**Comment by antioncodec** [comment]
Your opinion may be right. But I can't comfirm it since I only have one keybroad. My computer is 6 years old. Maybe it's time to upgrade it. 
But so far, this problem is most likely a software bug.Now I'm using a unoffcial version (I don't kown, maybe I should use "edition"?) , 06/09/18 - r8942, from http://plorkyeran.com/aegisub/ . Also, this problem occured at first. But it's strange that a few times later, this problem don't occur again.

> 
> 
> Your issue makes me think to a hardware problem. Try a different keyboard at first. It might be the motherboard as well, related to USB/PS2 juice or whatever it is. The chance that the problem comes from aegisub is very low IMO.
