### ISSUE TITLE
Flatpak Package & About the State of Aegisub

### ISSUE THREAD

**Issue by zefr0x** [Aegisub/Aegisub#336]
Hello,

I'm currently working in a [Flatpack](https://en.wikipedia.org/wiki/Flatpak) package for Aegisub to be published in [Flathub](https://flathub.org/) (I will reference it here as soon as its ready to be pushed to GitHub). So I would like to ask about the state of the project.

There was an attemt for a Flatpak package in https://github.com/Aegisub/Aegisub/issues/102, but it was rejected by Flathub, also it has a lot of patches and isn't organized.

I know that @CoffeeFlux is a member in @Aegisub, and also working in the [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub) fork to merge it soon with the main project. Also I know that the current lead developer of Aegisub @tgoyne is currently not working in the project any more.

The Aegisub **website** is currently maintained, but no release was made for the project itself since [v3.2.2](https://github.com/Aegisub/Aegisub/releases/tag/v3.2.2) in late 2014.

Debian is currently shipping the 9 year old release but with 28 [patches](https://salsa.debian.org/debian/aegisub/-/tree/bf52efb71f4b38f8127697116414c1ab9f7808b6/debian/patches).

There are plans for a 3.4.0 release by @CoffeeFlux in https://github.com/Aegisub/Aegisub/issues/214, but are done in [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub) without any patch/beta/alpha releases being made.

The current active forks that I was able to find are [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub) and [arch1t3cht/Aegisub](https://github.com/arch1t3cht/Aegisub) (@arch1t3cht is doing a great work, but not for production). Knowing that ArchLinux and Gentoo are currently packaging the no longer maintained [wangqr/Aegisub](https://github.com/wangqr/Aegisub) fork (@wangqr is not that active in GitHub, his fork is "focussing more on stability" as @arch1t3cht said) also it doesn't link with the latest version of libboost without a patch.

---

The Flathub package needs to be a representation of the main project as the main development team intended. I have few questions that I need an answer for to be able to properly package Aegisub as a Flatpak:

1. Is there any planes to create patch/beta/alpha releases tags in [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub)? Or does every commit in the master branch counts as a new patch/alpha release?
2. Should I base the package on the main repo, on [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub) or on [arch1t3cht/Aegisub](https://github.com/arch1t3cht/Aegisub)?

---

Thanks for every thing :)
I will create a new comment here when the package manifest is on GitHub, and some PRs to [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub) for upstream-side modifications.

**Comment by arch1t3cht** [comment]
I can answer some of those questions:

The reason why Aegisub/Aegisub is essentially frozen right now it that it's become pretty much unmaintainable due to its build system. That's why TypesettingTools/Aegisub started the effort to port the build system to meson, so that Aegisub could be developed again. This is almost done now, but there are a couple of remaining blockers that have to be worked out (some of them covered in #214 ). Work on that is progressing, albeit slowly.

Yes, wangqr/Aegisub is effectively dead as far as I can tell. I haven't seen wangqr being active anywhere for around a year.

> arch1t3cht is doing great work, but not for production.

It's probably my fault for making it seem that way in the README - this is something I wrote when first starting my fork, when it was mostly about developing experimental features. I've kept it around since the `feature` branch is fairly bleeding-edge and can cause regressions, so people shouldn't blindly pull from it when they're not aware of that. But I do also fix various bugs and give priority to fixing any issues caused by my changes, and the recent release tags should be fairly stable.

With that in mind:
> Is there any planes to create patch/beta/alpha releases tags in [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub)? Or does every commit in the master branch counts as a new patch/alpha release?

As far as I'm aware the plan is to merge TypesettingTools/Aegisub into Aegisub/Aegisub as soon as the remaining few issues are sorted out, so there likely won't be separate release tags on there. Its master is supposed to be fairly stable, though. That said, I don't think TypesettingTools/Aegisub builds with boost 1.81 right now (and neither does Aegisub/Aegisub, of course).

> Should I base the package on the main repo, on [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub) or on [arch1t3cht/Aegisub](https://github.com/arch1t3cht/Aegisub)?

That just depends on what you want. Feature-wise, TypesettingTools/Aegisub is not *too* different from Aegisub/Aegisub - the main difference is in the build system. If you want to save yourself some effort in the future, using TypesettingTools/Aegisub is probably easier. If you want the new feature additions in my fork, then you can base a package on my fork. Though then you should probably make clear that the package is based on a fork and not on official Aegisub.

**Comment by zefr0x** [comment]
This is the flatpak package that I'm working on: https://github.com/zefr0x/flathub/tree/aegisub

For now I built it on top of [wangqr/Aegisub](https://github.com/wangqr/Aegisub), but if this wasn't accepted by the Flathub team I will relay on [Aegisub/Aegisub](https://github.com/Aegisub/Aegisub) or [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub).

I will submit it to Flathub  after all issues are solved.

If any one want to test it or improve it, your contribution is welcomed.

**Comment by zefr0x** [comment]
Flatpak package is now at [flathub/org.aegisub.Aegisub](https://github.com/flathub/org.aegisub.Aegisub)
