### ISSUE TITLE
macOS: Audio volume/zoom sliders are broken

### ISSUE THREAD

**Issue by nielsmh** [Aegisub/Aegisub#64]
A certain macOS update triggered a possible latent bug in wxWidgets, which causes the audio box sliders used for volume control and zoom to malfunction.

The sliders appear to get created as horizontal sliders instead of vertical ones, so they have very little or no movement possible. This causes any attempt to manipulate them to set the function to minimum or maximum.

`src/audio_box.cpp` lines 66-68 are likely the culprit, changing the creation flags for the slider controls have fixed the bug in a previous test I made, but I didn't test it on other platforms, or get a fully functional build on macOS either.

**Comment by CoffeeFlux** [comment]
This appears to be fixed in the latest version of wxwidgets, so I assume it was some upstream issue. I can't find the particular commit at the moment, but I'm able to reproduce this on 10.13 only with the last of plork's osx trunk builds and not a fresh build with updated dependencies. Given that, I think the issue can just be marked as resolved - the only real change that needs to happen here is a new stable released with an updated osx build.

**Comment by tgoyne** [comment]
This was fixed by 3bc5e8f04f097ce70056be18f9919f643c0e37cb.

**Comment by LuRenJiasWorld** [comment]
For those who encounter the same issue: a build from 09/06/18 has contain the fix https://github.com/Aegisub/Aegisub/commit/3bc5e8f04f097ce70056be18f9919f643c0e37cb , you can download it from  [http://plorkyeran.com/aegisub/](http://plorkyeran.com/aegisub/) .

**Comment by superbrjn** [comment]
so, why don't you add this fix to a mac release?

**Comment by xth1227** [comment]
from https://zhuanlan.zhihu.com/p/105394202
[Aegisub-fix.dmg.zip](https://github.com/Aegisub/Aegisub/files/9879065/Aegisub-fix.dmg.zip)


> so, why don't you add this fix to a mac release?
