### ISSUE TITLE
check fonts can't refresh font cache on Windows 10 1809

### ISSUE THREAD

**Issue by txe0** [Aegisub/Aegisub#92]
Aegisub can't read the Font cache or refresh him on Windows 10 1809. The Font checker always say that all fonts are missing.

**Comment by ilko-k** [comment]
Builds 1803 and 1809 are known to have some bugs. One of them is that special characters are not properly rendered, even after updates. Font cache is perhaps involved, but I can tell you it's not related to aegisub. You must install another build, as I did.

**Comment by animefn** [comment]
it's because the recent versions of windows 10 allows "user fonts"(for each user) and "system fonts". I don't recall seeing this in early windows 10 versions. the font collector only look for system fonts but does not detect "user fonts". The workaround is to do right click on your fonts and install for all users. (need to do this for all fonts).

Please refer to this issue on another Aegisub fork: 
https://github.com/TypesettingTools/Aegisub/issues/73

**Comment by wangqr** [comment]
Have you tried to build the latest git repo? It should have been fixed in 896011f5355710c12f912f830ae32698d294cce9

**Comment by animefn** [comment]
@wangqr, I did not try to build it myself, I solved my issue by using "install for all users" which is faster and easier for me than compiling Aegisub  with visual studio. But I really hope some kind soul will do the dirty work for us and release new binaries soon! The latest official binaries are from 2014!!
